# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/adelin/projects/TerminalEmulator

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/adelin/projects/TerminalEmulator

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/adelin/projects/TerminalEmulator/CMakeFiles /home/adelin/projects/TerminalEmulator/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/adelin/projects/TerminalEmulator/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named TerminalSimulator

# Build rule for target.
TerminalSimulator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TerminalSimulator
.PHONY : TerminalSimulator

# fast build rule for target.
TerminalSimulator/fast:
	$(MAKE) -f CMakeFiles/TerminalSimulator.dir/build.make CMakeFiles/TerminalSimulator.dir/build
.PHONY : TerminalSimulator/fast

#=============================================================================
# Target rules for targets named hello

# Build rule for target.
hello: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hello
.PHONY : hello

# fast build rule for target.
hello/fast:
	$(MAKE) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/build
.PHONY : hello/fast

internalCommands/hello.o: internalCommands/hello.c.o
.PHONY : internalCommands/hello.o

# target to build an object file
internalCommands/hello.c.o:
	$(MAKE) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/internalCommands/hello.c.o
.PHONY : internalCommands/hello.c.o

internalCommands/hello.i: internalCommands/hello.c.i
.PHONY : internalCommands/hello.i

# target to preprocess a source file
internalCommands/hello.c.i:
	$(MAKE) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/internalCommands/hello.c.i
.PHONY : internalCommands/hello.c.i

internalCommands/hello.s: internalCommands/hello.c.s
.PHONY : internalCommands/hello.s

# target to generate assembly for a file
internalCommands/hello.c.s:
	$(MAKE) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/internalCommands/hello.c.s
.PHONY : internalCommands/hello.c.s

parser.o: parser.c.o
.PHONY : parser.o

# target to build an object file
parser.c.o:
	$(MAKE) -f CMakeFiles/TerminalSimulator.dir/build.make CMakeFiles/TerminalSimulator.dir/parser.c.o
.PHONY : parser.c.o

parser.i: parser.c.i
.PHONY : parser.i

# target to preprocess a source file
parser.c.i:
	$(MAKE) -f CMakeFiles/TerminalSimulator.dir/build.make CMakeFiles/TerminalSimulator.dir/parser.c.i
.PHONY : parser.c.i

parser.s: parser.c.s
.PHONY : parser.s

# target to generate assembly for a file
parser.c.s:
	$(MAKE) -f CMakeFiles/TerminalSimulator.dir/build.make CMakeFiles/TerminalSimulator.dir/parser.c.s
.PHONY : parser.c.s

pathBuilder.o: pathBuilder.c.o
.PHONY : pathBuilder.o

# target to build an object file
pathBuilder.c.o:
	$(MAKE) -f CMakeFiles/TerminalSimulator.dir/build.make CMakeFiles/TerminalSimulator.dir/pathBuilder.c.o
.PHONY : pathBuilder.c.o

pathBuilder.i: pathBuilder.c.i
.PHONY : pathBuilder.i

# target to preprocess a source file
pathBuilder.c.i:
	$(MAKE) -f CMakeFiles/TerminalSimulator.dir/build.make CMakeFiles/TerminalSimulator.dir/pathBuilder.c.i
.PHONY : pathBuilder.c.i

pathBuilder.s: pathBuilder.c.s
.PHONY : pathBuilder.s

# target to generate assembly for a file
pathBuilder.c.s:
	$(MAKE) -f CMakeFiles/TerminalSimulator.dir/build.make CMakeFiles/TerminalSimulator.dir/pathBuilder.c.s
.PHONY : pathBuilder.c.s

terminalSimulator.o: terminalSimulator.c.o
.PHONY : terminalSimulator.o

# target to build an object file
terminalSimulator.c.o:
	$(MAKE) -f CMakeFiles/TerminalSimulator.dir/build.make CMakeFiles/TerminalSimulator.dir/terminalSimulator.c.o
.PHONY : terminalSimulator.c.o

terminalSimulator.i: terminalSimulator.c.i
.PHONY : terminalSimulator.i

# target to preprocess a source file
terminalSimulator.c.i:
	$(MAKE) -f CMakeFiles/TerminalSimulator.dir/build.make CMakeFiles/TerminalSimulator.dir/terminalSimulator.c.i
.PHONY : terminalSimulator.c.i

terminalSimulator.s: terminalSimulator.c.s
.PHONY : terminalSimulator.s

# target to generate assembly for a file
terminalSimulator.c.s:
	$(MAKE) -f CMakeFiles/TerminalSimulator.dir/build.make CMakeFiles/TerminalSimulator.dir/terminalSimulator.c.s
.PHONY : terminalSimulator.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... TerminalSimulator"
	@echo "... edit_cache"
	@echo "... hello"
	@echo "... rebuild_cache"
	@echo "... internalCommands/hello.o"
	@echo "... internalCommands/hello.i"
	@echo "... internalCommands/hello.s"
	@echo "... parser.o"
	@echo "... parser.i"
	@echo "... parser.s"
	@echo "... pathBuilder.o"
	@echo "... pathBuilder.i"
	@echo "... pathBuilder.s"
	@echo "... terminalSimulator.o"
	@echo "... terminalSimulator.i"
	@echo "... terminalSimulator.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

